# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from trader.grpc_gen import trader_pb2 as trader__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in trader_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TraderControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/trader.v1.TraderControl/Health',
                request_serializer=trader__pb2.Empty.SerializeToString,
                response_deserializer=trader__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/trader.v1.TraderControl/GetState',
                request_serializer=trader__pb2.Empty.SerializeToString,
                response_deserializer=trader__pb2.RuntimeState.FromString,
                _registered_method=True)
        self.WatchRuntime = channel.unary_stream(
                '/trader.v1.TraderControl/WatchRuntime',
                request_serializer=trader__pb2.StreamRequest.SerializeToString,
                response_deserializer=trader__pb2.RuntimeState.FromString,
                _registered_method=True)
        self.PauseTrading = channel.unary_unary(
                '/trader.v1.TraderControl/PauseTrading',
                request_serializer=trader__pb2.Empty.SerializeToString,
                response_deserializer=trader__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ResumeTrading = channel.unary_unary(
                '/trader.v1.TraderControl/ResumeTrading',
                request_serializer=trader__pb2.Empty.SerializeToString,
                response_deserializer=trader__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.UpdateStop = channel.unary_unary(
                '/trader.v1.TraderControl/UpdateStop',
                request_serializer=trader__pb2.StopUpdateRequest.SerializeToString,
                response_deserializer=trader__pb2.RuntimeState.FromString,
                _registered_method=True)


class TraderControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRuntime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseTrading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeTrading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraderControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=trader__pb2.Empty.FromString,
                    response_serializer=trader__pb2.HealthResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=trader__pb2.Empty.FromString,
                    response_serializer=trader__pb2.RuntimeState.SerializeToString,
            ),
            'WatchRuntime': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRuntime,
                    request_deserializer=trader__pb2.StreamRequest.FromString,
                    response_serializer=trader__pb2.RuntimeState.SerializeToString,
            ),
            'PauseTrading': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseTrading,
                    request_deserializer=trader__pb2.Empty.FromString,
                    response_serializer=trader__pb2.ActionResponse.SerializeToString,
            ),
            'ResumeTrading': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeTrading,
                    request_deserializer=trader__pb2.Empty.FromString,
                    response_serializer=trader__pb2.ActionResponse.SerializeToString,
            ),
            'UpdateStop': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStop,
                    request_deserializer=trader__pb2.StopUpdateRequest.FromString,
                    response_serializer=trader__pb2.RuntimeState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trader.v1.TraderControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trader.v1.TraderControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TraderControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trader.v1.TraderControl/Health',
            trader__pb2.Empty.SerializeToString,
            trader__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trader.v1.TraderControl/GetState',
            trader__pb2.Empty.SerializeToString,
            trader__pb2.RuntimeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRuntime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/trader.v1.TraderControl/WatchRuntime',
            trader__pb2.StreamRequest.SerializeToString,
            trader__pb2.RuntimeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PauseTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trader.v1.TraderControl/PauseTrading',
            trader__pb2.Empty.SerializeToString,
            trader__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeTrading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trader.v1.TraderControl/ResumeTrading',
            trader__pb2.Empty.SerializeToString,
            trader__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trader.v1.TraderControl/UpdateStop',
            trader__pb2.StopUpdateRequest.SerializeToString,
            trader__pb2.RuntimeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
